<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
<!ELEMENT books (book)+><!--Space is required!!!-->
<!ELEMENT book (heading , author , category , publisher , pages)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT pages (#PCDATA)>

<!ATTLIST book id CDATA #REQUIRED>
]>
<books>

<book id="1">
<heading>Upijajuci um</heading>
<author>Marija Montesori</author>
<category>PEDAGOGY</category>
<publisher>MIBA BOOKS</publisher>
<pages>399</pages>
</book>

<book id="2">
<heading>Hristos Voskrese, radosti moja. - Sveti Serafim Sarovski - Prorok Bozije ljubavi</heading>
<author>Jovan Srbulj</author>
<category>RELIGION</category>
<publisher>Orthodox missionary school at the temple of Saint Alexander Nevsky</publisher>
<pages>664</pages>
</book>

<book id="3">
<heading>Tragedija genija</heading>
<author>Vladimir Stanojevic</author>
<category>PSYCHOLOGY</category>
<publisher>Neven</publisher>
<pages>430</pages>
</book>



</books>
